### ISSUE TITLE
SSM params don't exist

### ISSUE THREAD

**Issue by Denelvo** [jvanbuel/better-infrastructure-management-with-terraform#1]
https://github.com/jvanbuel/better-infrastructure-management-with-terraform/blob/040dfc41914f5af061204e78bd2c9584c5796783/05_count_for_each/secure_notebook/notebook_instance.tf#L7

Something is wrong here. There's a copy/paste error on line 7, but also: when planning, the SSM params don't exist. Are they supposed to be part of the infra provided for the exercise, or are students supposed to create them?

**Comment by jvanbuel** [comment]
These SSM params are indeed already available, but the SSM params live at a different path. Thanks for catching it! Fixed in https://github.com/jvanbuel/better-infrastructure-management-with-terraform/commit/ce25d5b7ff9180620c5fcc2e5a738301b7fc4fe1 .
